# Generated by Django 4.1.5 on 2023-02-21 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentApp', '0002_virtualcounsellor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='virtualcounsellor',
            old_name='main',
            new_name='mail',
        ),
    ]
