# Generated by Django 4.1.5 on 2023-02-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentApp', '0003_rename_main_virtualcounsellor_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(max_length=256),
        ),
        migrations.AlterField(
            model_name='virtualcounsellor',
            name='mail',
            field=models.EmailField(max_length=256),
        ),
    ]
