# Generated by Django 4.1.5 on 2023-03-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentApp', '0004_alter_appointment_email_alter_virtualcounsellor_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(max_length=256),
        ),
    ]
