# Generated by Django 4.1.3 on 2022-12-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='phonenumber',
            field=models.IntegerField(default=0),
        ),
    ]
