# Generated by Django 4.1.5 on 2023-01-19 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_message_score_alter_message_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sent_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
