# Generated by Django 4.1.5 on 2023-01-19 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_predresults_sent_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predresults',
            old_name='sent_date',
            new_name='date',
        ),
    ]
