# Generated by Django 4.1.5 on 2023-01-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_message_sent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predresults',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
