# Generated by Django 4.1.5 on 2023-01-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_predresults_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='resultMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=256)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
