# Generated by Django 4.1.5 on 2023-01-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_contactmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='ReferralMessage',
        ),
    ]
