# Generated by Django 4.1.5 on 2023-01-27 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_rename_message_referralmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
