# Generated by Django 4.1.5 on 2023-02-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_predictedresult_id_predictedresult_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictedresult',
            name='user_id',
        ),
        migrations.AddField(
            model_name='predictedresult',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
